#+OPTIONS: toc:nil num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{soul}
#+LATEX_HEADER: \definecolor{foreground}{RGB}{184, 83, 83}
#+LATEX_HEADER: \definecolor{background}{RGB}{255, 231, 231}
#+LATEX_HEADER: \let\OldTexttt\texttt
#+LATEX_HEADER: \renewcommand{\texttt}[1]{\OldTexttt{\colorbox{background}{\textcolor{foreground}{#1}}}}

#+BEGIN_EXPORT latex
% This is the title page
\thispagestyle{empty} % No page number on the first page
\begin{center}
  {\Huge\textbf{SOFE 3980U}\par}
  \vspace{60mm}
  \includegraphics[scale=1.3]{./img/uoit_logo.png}\\
  \vspace{40mm}
  \begin{Large}
      \textbf{Assignment 2, Report}\\
      \textbf{Tic-Tac-Toe}\\
      \vspace{20mm}
      \textbf{Justin Kaipada 100590167}
  \end{Large}
\end{center}
\newpage
#+END_EXPORT

* Development process

For the development of the game I followed agile development
process. Although 3 weeks is more than enough time for a small game
like *tic-tac-toe*, the simplicity of the project works well with agile
development the most. Incremented development or Waterfall was
unnecessarily complex for this small project. Doing agile development,
I was already experienced with *Continuous Integration* for both GNU
Linux and Windows environments. This helped me to support and make
sure that my source code can be compiled and ran on both the platforms
from the beginning.

* Functionality

My project implements a simple *tic-tac-toe* game.
